'use strict';

const { bus } = require('../events/bus.cjs');
const persistence = require('../db/persistence.cjs');

/**
 * CHATR Intelligence Platform — Executive Feed (v2)
 * Phase 8 - Real Data & Kernel Execution
 *
 * Reads actual execution outcomes from the SQLite database
 * instead of relying on mock events.
 */
class ExecutiveFeed {
  constructor() {
    this.attention = [];

    // Listen for real attention needs (conflicts, opportunities generated by real reasoning)
    bus.subscribe('intelligence.attention.needed', (e) => {
      this.attention.push({
        id: `a_${Date.now()}_${Math.floor(Math.random()*1000)}`,
        text: e.payload.text,
        source: e.payload.source
      });
    });
  }

  /**
   * Retrieves the current briefing state from the REAL database.
   */
  getBriefing() {
    // 1. Fetch real Completed Executions from the database for today
    // In a production app, we would query `execution_outcomes` for today's date.
    let completedRows = [];
    try {
      const stmt = persistence.db.prepare(`
        SELECT * FROM execution_outcomes 
        WHERE status = 'SUCCESS' 
        ORDER BY timestamp DESC 
        LIMIT 20
      `);
      completedRows = stmt.all();
    } catch (e) {
      console.error('[ExecutiveFeed] Failed to fetch real executions:', e.message);
    }

    const formattedCompleted = completedRows.map(row => {
      let text = `Executed ${row.type}`;
      try {
        if (row.metadata) {
          const meta = JSON.parse(row.metadata);
          if (meta.action_description) text = meta.action_description;
        }
      } catch (e) {}

      return {
        id: row.id,
        text: text,
        canUndo: true // Real executions via the Kernel can potentially be reverted
      };
    });

    return {
      completed: formattedCompleted,
      attention: this.attention,
      estimatedTime: `${Math.max(1, Math.ceil(this.attention.length * 1.5))} minutes`
    };
  }

  clear() {
    this.attention = [];
  }
}

const executiveFeed = new ExecutiveFeed();
module.exports = { ExecutiveFeed, executiveFeed };
