packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  '@swc/core': true
  better-sqlite3: true
  canvas: true
  core-js: true
  electron-winstaller: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  puppeteer: true
  sharp: true
  tesseract.js: true
