export type EventLevel = 'info' | 'warn' | 'error' | 'critical';

export interface EventMetadata {
  sourceSubsystem: string;     // e.g., 'GoalEngine', 'PackageManager'
  timestamp: string;           // ISO8601
  confidence?: number;         // 0.0 - 1.0 (if generated by AI/heuristics)
  verificationStatus?: 'unverified' | 'verified' | 'failed';
  provenance: string;          // Trace ID or original signal ID that caused this
  schemaVersion: string;
  producerVersion: string;
  platformVersion: string;
}

export interface OSEvent {
  id: string;                  // UUID
  type: string;                // e.g., 'reality.entity_created', 'execution.failed'
  level: EventLevel;
  metadata: EventMetadata;
  payload: Record<string, any>;
}

export interface EventLogABI {
  append(event: Omit<OSEvent, 'id' | 'metadata'> & { metadata: Partial<EventMetadata> }): Promise<string>;
  query(filter: { type?: string; sourceSubsystem?: string; since?: string }): Promise<OSEvent[]>;
  replay(sinceId: string, targetSubsystem: string): Promise<void>;
}
