import { CallerIntelligence } from './types';

export const mockCallers: Record<string, CallerIntelligence> = {
  // TEST FIXTURE — fictional numbers only. Never use real phone numbers in mock data.
  "+919999900001": {
    phoneNumber: "+919999900001",
    displayName: "Chatr Dev Alpha",
    isContact: true,
    isBusiness: false,
    businessName: null,
    businessCategory: null,
    businessLogoUrl: null,
    isVerified: true,
    trustScore: 95,
    trustBand: "safe",
    confidenceLevel: "high",
    communityReportCount: 0,
    communityLookupCount: 12,
    communityTags: [],
    webIdentity: null,
    carrierData: {
      operator: "Jio",
      numberType: "mobile",
      state: "Delhi",
      isVoip: false,
      numberAgeMonths: 48,
      cliMismatch: false
    },
    aiSummary: "Saved contact. Safe to answer.",
    aiFlags: [],
    lastActive: "2 mins ago",
  },
  "+919999900002": {
    phoneNumber: "+919999900002",
    displayName: "Chatr Dev Beta",
    isContact: true,
    isBusiness: false,
    businessName: null,
    businessCategory: null,
    businessLogoUrl: null,
    isVerified: true,
    trustScore: 92,
    trustBand: "safe",
    confidenceLevel: "high",
    communityReportCount: 0,
    communityLookupCount: 8,
    communityTags: [],
    webIdentity: null,
    carrierData: {
      operator: "Airtel",
      numberType: "mobile",
      state: "Delhi",
      isVoip: false,
      numberAgeMonths: 36,
      cliMismatch: false
    },
    aiSummary: "Saved contact. Safe to answer.",
    aiFlags: [],
    lastActive: "14 mins ago",
  },
  "+919717815470": {
    phoneNumber: "+919717815470",
    displayName: null,
    isContact: false,
    isBusiness: false,
    businessName: null,
    businessCategory: null,
    businessLogoUrl: null,
    isVerified: false,
    trustScore: 50,
    trustBand: "verify",
    confidenceLevel: "medium",
    communityReportCount: 0,
    communityLookupCount: 1727,
    communityTags: ["Unverified"],
    webIdentity: null,
    carrierData: {
      operator: "BSNL",
      numberType: "mobile",
      state: "Uttar Pradesh",
      isVoip: false,
      numberAgeMonths: null,
      cliMismatch: false
    },
    aiSummary: "Limited identity history. Verify before sharing details.",
    aiFlags: ["Limited trust history", "1,727 community lookups", "No recent Chatr history"],
    lastActive: "118 mins ago",
  },
  "+918001234567": {
    phoneNumber: "+918001234567",
    displayName: null,
    isContact: false,
    isBusiness: true,
    businessName: "HDFC Bank Customer Care",
    businessCategory: "Banking & Finance",
    businessLogoUrl: null,
    isVerified: true,
    trustScore: 88,
    trustBand: "safe",
    confidenceLevel: "high",
    communityReportCount: 2,
    communityLookupCount: 94820,
    communityTags: ["Bank"],
    webIdentity: {
      businessName: "HDFC Bank Ltd",
      category: "Banking",
      traiDndRegistered: false,
      webMentionsCount: 4200,
      sentiment: "positive",
      sourceUrls: ["hdfcbank.com"],
    },
    carrierData: {
      operator: "Airtel",
      numberType: "tollfree",
      state: "Maharashtra",
      isVoip: false,
      numberAgeMonths: 120,
      cliMismatch: false
    },
    aiSummary: "Verified HDFC Bank customer care line. Legitimate.",
    aiFlags: [],
    lastActive: "5 mins ago",
  },
  "+919876500000": {
    phoneNumber: "+919876500000",
    displayName: null,
    isContact: false,
    isBusiness: false,
    businessName: null,
    businessCategory: null,
    businessLogoUrl: null,
    isVerified: false,
    trustScore: 12,
    trustBand: "block",
    confidenceLevel: "high",
    communityReportCount: 847,
    communityLookupCount: 23400,
    communityTags: ["Telemarketer", "Scam", "Loan"],
    webIdentity: {
      businessName: null,
      category: null,
      traiDndRegistered: true,
      webMentionsCount: 320,
      sentiment: "negative",
      sourceUrls: [],
    },
    carrierData: {
      operator: "Vi",
      numberType: "mobile",
      state: "Rajasthan",
      isVoip: false,
      numberAgeMonths: 3,
      cliMismatch: true
    },
    aiSummary: "High risk. 847 spam reports in 30 days. TRAI DND registered telemarketer.",
    aiFlags: [
      "847 community spam reports",
      "TRAI DND registered",
      "CLI mismatch detected",
      "Number age: 3 months (high churn)",
    ],
    lastActive: "Just now",
  },
};
