import { chatrAIToolRegistry } from './ToolRegistry';
import type { ChatrAIToolDefinition } from './types';

export const coreChatrAITools: ChatrAIToolDefinition[] = [
  {
    id: 'conversation.timeline.read',
    name: 'Conversation Timeline',
    description: 'Read conversation timeline context through the Conversation API.',
    version: '1.0.0',
    category: 'conversation',
    requiredPermissions: ['conversation:read'],
    riskLevel: 'low',
    requiresApproval: false,
    status: 'available',
    surfaces: ['mobile', 'desktop', 'business', 'enterprise'],
    eventTypes: ['conversation.context.read'],
    guardrails: ['Use platform API context only.', 'Do not infer missing timeline events.'],
  },
  {
    id: 'messaging.draft',
    name: 'Message Drafting',
    description: 'Draft replies without sending them.',
    version: '1.0.0',
    category: 'messaging',
    requiredPermissions: ['message:draft'],
    riskLevel: 'low',
    requiresApproval: false,
    status: 'available',
    surfaces: ['mobile', 'desktop', 'business', 'enterprise'],
    eventTypes: ['message.draft.created'],
    guardrails: ['Never send without explicit user action.', 'Show generated text before use.'],
  },
  {
    id: 'messaging.send',
    name: 'Send Message',
    description: 'Send a message through the Messaging API.',
    version: '1.0.0',
    category: 'messaging',
    requiredPermissions: ['message:send'],
    riskLevel: 'medium',
    requiresApproval: true,
    status: 'metadata_only',
    surfaces: ['mobile', 'desktop', 'business', 'enterprise'],
    eventTypes: ['message.sent'],
    guardrails: ['Requires explicit confirmation.', 'Route through Messaging API only.'],
  },
  {
    id: 'calling.place_call',
    name: 'Place Call',
    description: 'Prepare a call through the Calling API.',
    version: '1.0.0',
    category: 'calling',
    requiredPermissions: ['call:place'],
    riskLevel: 'high',
    requiresApproval: true,
    status: 'metadata_only',
    surfaces: ['mobile', 'desktop', 'business', 'enterprise'],
    eventTypes: ['call.requested', 'call.started', 'call.ended'],
    guardrails: ['Never starts media directly.', 'Requires explicit user action.', 'Use Calling API only.'],
  },
  {
    id: 'calendar.event.draft',
    name: 'Calendar Draft',
    description: 'Create calendar event drafts from conversation context.',
    version: '1.0.0',
    category: 'calendar',
    requiredPermissions: ['calendar:draft'],
    riskLevel: 'low',
    requiresApproval: false,
    status: 'available',
    surfaces: ['mobile', 'desktop', 'business', 'enterprise'],
    eventTypes: ['calendar.draft.created'],
    guardrails: ['Do not add events without confirmation.', 'Use exact dates when available.'],
  },
  {
    id: 'browser.search',
    name: 'AI Browser Search',
    description: 'Search the web through approved browser/search tools.',
    version: '1.0.0',
    category: 'browser',
    requiredPermissions: ['browser:search'],
    riskLevel: 'medium',
    requiresApproval: false,
    status: 'available',
    surfaces: ['mobile', 'desktop', 'business', 'enterprise'],
    eventTypes: ['browser.search.requested'],
    guardrails: ['Cite sources for external facts.', 'Do not submit forms without confirmation.'],
  },
  {
    id: 'workflow.run',
    name: 'Workflow Runner',
    description: 'Start approved workflow runs through the Workflow Engine.',
    version: '1.0.0',
    category: 'workflow',
    requiredPermissions: ['workflow:run'],
    riskLevel: 'medium',
    requiresApproval: true,
    status: 'metadata_only',
    surfaces: ['desktop', 'business', 'enterprise'],
    eventTypes: ['workflow.run.requested', 'workflow.run.started'],
    guardrails: ['Use workflow definitions only.', 'Require approval for side effects.'],
  },
  {
    id: 'crm.update_record',
    name: 'CRM Update',
    description: 'Prepare CRM status updates from conversation outcomes.',
    version: '1.0.0',
    category: 'crm',
    requiredPermissions: ['crm:update'],
    riskLevel: 'medium',
    requiresApproval: true,
    status: 'metadata_only',
    surfaces: ['business', 'enterprise', 'desktop'],
    eventTypes: ['crm.record.update_requested'],
    guardrails: ['Show before saving.', 'Preserve audit trail.'],
  },
  {
    id: 'payments.initiate',
    name: 'Payment Action',
    description: 'Prepare payment actions for explicit user confirmation.',
    version: '1.0.0',
    category: 'payments',
    requiredPermissions: ['payment:initiate'],
    riskLevel: 'high',
    requiresApproval: true,
    status: 'metadata_only',
    surfaces: ['mobile', 'business', 'enterprise'],
    eventTypes: ['payment.action.requested'],
    guardrails: ['Never execute without confirmation.', 'Require audit event and risk check.'],
  },
  {
    id: 'notifications.draft',
    name: 'Notification Draft',
    description: 'Prepare notification copy and routing metadata.',
    version: '1.0.0',
    category: 'notifications',
    requiredPermissions: ['notification:draft'],
    riskLevel: 'low',
    requiresApproval: false,
    status: 'available',
    surfaces: ['mobile', 'desktop', 'business', 'enterprise'],
    eventTypes: ['notification.draft.created'],
    guardrails: ['Respect quiet hours.', 'Do not send without Notification API policy.'],
  },
];

chatrAIToolRegistry.registerMany(coreChatrAITools);
