import React, { useState } from 'react';
import { Brain, ChevronDown, ChevronUp, Clock, CheckCircle2, AlertTriangle, Sparkles } from 'lucide-react';

export interface CallSummaryData {
 phoneNumber: string;
 contactName?: string;
 durationSeconds: number;
 summary: string;
 keyPoints: string[];
 followUps: string[];
 sentiment: 'positive' | 'neutral' | 'negative' | 'scam_risk';
 generatedAt: number;
}

interface AISummaryCardProps {
 summary: CallSummaryData;
 themeColor?: string;
}

function formatDuration(seconds: number): string {
 if (seconds < 60) return `${seconds}s`;
 const m = Math.floor(seconds / 60);
 const s = seconds % 60;
 return s > 0 ? `${m}m ${s}s` : `${m}m`;
}

function formatTimeAgo(ts: number): string {
 const diff = (Date.now() - ts) / 1000;
 if (diff < 60) return 'Just now';
 if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
 if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
 return new Date(ts).toLocaleDateString();
}

const sentimentConfig = {
 positive: { color: '#22C55E', label: 'Positive', icon: CheckCircle2 },
 neutral: { color: '#6B7280', label: 'Neutral', icon: CheckCircle2 },
 negative: { color: '#F59E0B', label: 'Negative', icon: AlertTriangle },
 scam_risk:{ color: '#EF4444', label: '⚠ Scam Risk', icon: AlertTriangle },
};

export const AISummaryCard: React.FC<AISummaryCardProps> = ({ summary, themeColor = '#8B5CF6' }) => {
 const [expanded, setExpanded] = useState(false);
 const sentiment = sentimentConfig[summary.sentiment] ?? sentimentConfig.neutral;
 const SentimentIcon = sentiment.icon;

 return (
 <div
 className="mx-4 mb-3 rounded-2xl border overflow-hidden"
 style={{
 background: 'linear-gradient(135deg, rgba(139,92,246,0.08) 0%, rgba(99,102,241,0.04) 100%)',
 borderColor: themeColor + '33',
 boxShadow: `0 4px 24px ${themeColor}1A`,
 }}
 >
 {/* Header row */}
 <button
 className="w-full flex items-center gap-3 px-4 py-3 text-left"
 onClick={() => setExpanded(e => !e)}
 >
 {/* Brain icon */}
 <div
 className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0"
 style={{ background: themeColor + '22' }}
 >
 <Brain size={18} style={{ color: themeColor }} />
 </div>

 <div className="flex-1 min-w-0">
 <div className="flex items-center gap-2">
 <span className="text-[13px] font-bold text-white/90">Chatr AI Summary</span>
 <span
 className="text-[10px] font-bold px-2 py-0.5 rounded-full"
 style={{ background: sentiment.color + '22', color: sentiment.color }}
 >
 {sentiment.label}
 </span>
 </div>
 <p className="text-[12px] text-white/50 truncate mt-0.5">{summary.summary}</p>
 </div>

 <div className="flex items-center gap-2 shrink-0">
 <div className="flex items-center gap-1 text-white/30">
 <Clock size={11} />
 <span className="text-[11px]">{formatDuration(summary.durationSeconds)}</span>
 </div>
 {expanded
 ? <ChevronUp size={16} className="text-white/40" />
 : <ChevronDown size={16} className="text-white/40" />
 }
 </div>
 </button>

 {/* Expanded content */}
 {expanded && (
 <div className="px-4 pb-4 space-y-3 border-t border-white/[0.06] pt-3">

 {/* Full summary */}
 <p className="text-[13px] text-white/70 leading-relaxed">{summary.summary}</p>

 {/* Key Points */}
 {summary.keyPoints.length > 0 && (
 <div>
 <div className="flex items-center gap-1.5 mb-2">
 <Sparkles size={12} style={{ color: themeColor }} />
 <span className="text-[11px] font-bold uppercase tracking-wider" style={{ color: themeColor }}>Key Points</span>
 </div>
 <ul className="space-y-1.5">
 {summary.keyPoints.map((point, i) => (
 <li key={i} className="flex items-start gap-2">
 <div className="w-1.5 h-1.5 rounded-full mt-1.5 shrink-0" style={{ background: themeColor }} />
 <span className="text-[12px] text-white/65">{point}</span>
 </li>
 ))}
 </ul>
 </div>
 )}

 {/* Follow-ups */}
 {summary.followUps.length > 0 && (
 <div>
 <div className="flex items-center gap-1.5 mb-2">
 <CheckCircle2 size={12} className="text-green-400" />
 <span className="text-[11px] font-bold uppercase tracking-wider text-green-400">Follow-ups</span>
 </div>
 <ul className="space-y-1.5">
 {summary.followUps.map((item, i) => (
 <li key={i} className="flex items-start gap-2">
 <div className="w-1.5 h-1.5 rounded-full mt-1.5 shrink-0 bg-green-400" />
 <span className="text-[12px] text-white/65">{item}</span>
 </li>
 ))}
 </ul>
 </div>
 )}

 {/* Footer */}
 <div className="flex items-center justify-between pt-1 border-t border-white/[0.06]">
 <span className="text-[10px] text-white/25">Generated by Chatr AI · {formatTimeAgo(summary.generatedAt)}</span>
 <SentimentIcon size={12} style={{ color: sentiment.color }} />
 </div>
 </div>
 )}
 </div>
 );
};

export default AISummaryCard;
