-- ==============================================================================
-- CHATR CORE V1 SCHEMA
-- This file defines the foundation for chatr-core.
-- Do not edit this file directly after it has been applied to production.
-- ==============================================================================

-- Enable essential extensions
create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

-- ==============================================================================
-- 1. IDENTITIES & ACCESS
-- ==============================================================================

-- USERS
create table if not exists public.users (
  id uuid references auth.users on delete cascade primary key,
  username text unique not null,
  full_name text,
  avatar_url text,
  status text default 'offline',
  last_seen timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);
alter table public.users enable row level security;
create policy "Public active users are viewable by everyone" on public.users for select using (true);
create policy "Users can update own profile" on public.users for update using (auth.uid() = id);

-- ORGANIZATIONS
create table if not exists public.organizations (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  slug text unique not null,
  logo_url text,
  settings jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now()
);
alter table public.organizations enable row level security;
-- RLS applied later when organization_members is created

-- ORGANIZATION MEMBERS
create type org_role as enum ('owner', 'admin', 'member', 'guest');
create table if not exists public.organization_members (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  user_id uuid references public.users(id) on delete cascade not null,
  role org_role default 'member' not null,
  created_at timestamp with time zone default now(),
  unique(organization_id, user_id)
);
alter table public.organization_members enable row level security;

-- Now add Org policies
create policy "Org members can view organizations" on public.organizations for select 
  using (exists (select 1 from public.organization_members where organization_id = id and user_id = auth.uid()));
create policy "Org admins can update organizations" on public.organizations for update 
  using (exists (select 1 from public.organization_members where organization_id = id and user_id = auth.uid() and role in ('owner', 'admin')));
  
create policy "Org members can view members" on public.organization_members for select 
  using (exists (select 1 from public.organization_members m where m.organization_id = organization_id and m.user_id = auth.uid()));

-- ==============================================================================
-- 2. COMMUNICATION CORE
-- ==============================================================================

-- CONVERSATIONS
create type conversation_type as enum ('direct', 'group', 'channel');
create table if not exists public.conversations (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade,
  type conversation_type not null,
  name text,
  metadata jsonb default '{}'::jsonb,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now()
);
alter table public.conversations enable row level security;

-- CONVERSATION PARTICIPANTS
create table if not exists public.conversation_participants (
  id uuid default gen_random_uuid() primary key,
  conversation_id uuid references public.conversations(id) on delete cascade not null,
  user_id uuid references public.users(id) on delete cascade not null,
  role text default 'member',
  last_read_at timestamp with time zone default now(),
  unique(conversation_id, user_id)
);
alter table public.conversation_participants enable row level security;

-- Conversation policies
create policy "Participants can view conversations" on public.conversations for select 
  using (exists (select 1 from public.conversation_participants where conversation_id = id and user_id = auth.uid()));
create policy "Participants can view other participants" on public.conversation_participants for select 
  using (exists (select 1 from public.conversation_participants p where p.conversation_id = conversation_id and p.user_id = auth.uid()));

-- MESSAGES
create type message_type as enum ('text', 'system', 'ai');
create table if not exists public.messages (
  id uuid default gen_random_uuid() primary key,
  conversation_id uuid references public.conversations(id) on delete cascade not null,
  sender_id uuid references public.users(id) on delete set null,
  content text not null,
  type message_type default 'text',
  created_at timestamp with time zone default now()
);
alter table public.messages enable row level security;
create policy "Participants can view messages" on public.messages for select 
  using (exists (select 1 from public.conversation_participants where conversation_id = messages.conversation_id and user_id = auth.uid()));
create policy "Participants can insert messages" on public.messages for insert 
  with check (exists (select 1 from public.conversation_participants where conversation_id = messages.conversation_id and user_id = auth.uid()));

-- ATTACHMENTS
create table if not exists public.attachments (
  id uuid default gen_random_uuid() primary key,
  message_id uuid references public.messages(id) on delete cascade not null,
  file_url text not null,
  file_type text not null,
  size_bytes bigint not null,
  name text,
  created_at timestamp with time zone default now()
);
alter table public.attachments enable row level security;
create policy "Readers can view attachments" on public.attachments for select 
  using (exists (
    select 1 from public.messages m 
    join public.conversation_participants cp on cp.conversation_id = m.conversation_id
    where m.id = attachments.message_id and cp.user_id = auth.uid()
  ));

-- ==============================================================================
-- 3. VOICE & VIDEO
-- ==============================================================================

-- CALLS
create type call_status as enum ('ringing', 'active', 'ended', 'missed');
create table if not exists public.calls (
  id uuid default gen_random_uuid() primary key,
  conversation_id uuid references public.conversations(id) on delete cascade not null,
  caller_id uuid references public.users(id) on delete cascade not null,
  status call_status default 'ringing',
  started_at timestamp with time zone default now(),
  ended_at timestamp with time zone
);
alter table public.calls enable row level security;
create policy "Participants can view calls" on public.calls for select 
  using (exists (select 1 from public.conversation_participants where conversation_id = calls.conversation_id and user_id = auth.uid()));

-- MEETINGS
create table if not exists public.meetings (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  host_id uuid references public.users(id) on delete cascade not null,
  title text not null,
  scheduled_for timestamp with time zone,
  status text default 'scheduled',
  join_code text unique not null,
  created_at timestamp with time zone default now()
);
alter table public.meetings enable row level security;
create policy "Org members can view meetings" on public.meetings for select 
  using (exists (select 1 from public.organization_members where organization_id = meetings.organization_id and user_id = auth.uid()));

-- MEETING PARTICIPANTS
create table if not exists public.meeting_participants (
  id uuid default gen_random_uuid() primary key,
  meeting_id uuid references public.meetings(id) on delete cascade not null,
  user_id uuid references public.users(id) on delete cascade not null,
  joined_at timestamp with time zone default now(),
  left_at timestamp with time zone
);
alter table public.meeting_participants enable row level security;

-- ==============================================================================
-- 4. AI & INTELLIGENCE
-- ==============================================================================

create table if not exists public.ai_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  agent_role text not null,
  context_window jsonb default '{}'::jsonb,
  status text default 'active',
  created_at timestamp with time zone default now()
);
alter table public.ai_sessions enable row level security;
create policy "Users manage own AI sessions" on public.ai_sessions for all using (user_id = auth.uid());

create table if not exists public.ai_memory (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) on delete cascade,
  organization_id uuid references public.organizations(id) on delete cascade,
  fact text not null,
  confidence_score numeric(3,2),
  created_at timestamp with time zone default now()
);
alter table public.ai_memory enable row level security;

-- ==============================================================================
-- 5. INFRASTRUCTURE & AUDIT
-- ==============================================================================

create table if not exists public.notifications (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  type text not null,
  title text not null,
  body text,
  action_url text,
  read_at timestamp with time zone,
  created_at timestamp with time zone default now()
);
alter table public.notifications enable row level security;
create policy "Users manage own notifications" on public.notifications for all using (user_id = auth.uid());

create table if not exists public.storage_metadata (
  id uuid default gen_random_uuid() primary key,
  bucket_name text not null,
  path text not null,
  owner_id uuid references public.users(id) on delete set null,
  organization_id uuid references public.organizations(id) on delete cascade,
  size_bytes bigint not null,
  created_at timestamp with time zone default now()
);
alter table public.storage_metadata enable row level security;

create table if not exists public.audit_logs (
  id uuid default gen_random_uuid() primary key,
  organization_id uuid references public.organizations(id) on delete cascade not null,
  actor_id uuid references public.users(id) on delete set null,
  action text not null,
  resource_type text not null,
  resource_id text,
  details jsonb default '{}'::jsonb,
  created_at timestamp with time zone default now()
);
alter table public.audit_logs enable row level security;
-- Deny updates/deletes entirely
create policy "Nobody can update audit logs" on public.audit_logs for update using (false);
create policy "Nobody can delete audit logs" on public.audit_logs for delete using (false);
create policy "Org admins can view audit logs" on public.audit_logs for select 
  using (exists (select 1 from public.organization_members where organization_id = audit_logs.organization_id and user_id = auth.uid() and role in ('owner', 'admin')));
