-- Release Gate 2: Value Analytics Subsystem
-- This schema tracks commercial business value generated by the platform.

-- 1. Value Metrics (Tracking absolute time & attention saved)
CREATE TABLE IF NOT EXISTS value_metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id TEXT NOT NULL,
    workflow_id UUID NOT NULL, 
    goal_id UUID NOT NULL,
    
    baseline_manual_seconds INTEGER NOT NULL, -- The time a human used to take
    autonomous_execution_seconds INTEGER NOT NULL, -- The time CHATR took
    time_saved_seconds INTEGER GENERATED ALWAYS AS (baseline_manual_seconds - autonomous_execution_seconds) STORED,
    
    attention_clicks_saved INTEGER NOT NULL DEFAULT 0, -- Context switches eliminated
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_value_metrics_tenant ON value_metrics(tenant_id);

-- 2. Operator Trust (Tracking human delegation choices post-execution)
CREATE TABLE IF NOT EXISTS operator_trust (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id TEXT NOT NULL,
    goal_id UUID NOT NULL,
    operator_id TEXT NOT NULL,
    
    -- "Would you delegate this again?"
    trust_level TEXT NOT NULL CHECK (trust_level IN ('delegated_blind', 'delegated_with_review', 'rejected')),
    feedback_notes TEXT,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Intervention Log (Tracking the drop in manual interventions over time)
CREATE TABLE IF NOT EXISTS intervention_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id TEXT NOT NULL,
    goal_id UUID NOT NULL,
    
    -- When the platform pauses execution to ask a human for help
    intervention_type TEXT NOT NULL CHECK (intervention_type IN ('policy_escalation', 'ambiguity_resolution', 'credential_request')),
    resolution_time_seconds INTEGER NOT NULL,
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- RLS Enforcement
ALTER TABLE value_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE operator_trust ENABLE ROW LEVEL SECURITY;
ALTER TABLE intervention_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow selects on value metrics" ON value_metrics FOR SELECT USING (true);
CREATE POLICY "Allow selects on operator trust" ON operator_trust FOR SELECT USING (true);
CREATE POLICY "Allow selects on intervention log" ON intervention_log FOR SELECT USING (true);

CREATE POLICY "Allow inserts on value metrics" ON value_metrics FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow inserts on operator trust" ON operator_trust FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow inserts on intervention log" ON intervention_log FOR INSERT WITH CHECK (true);
